### ISSUE TITLE
Please update heroku CLI to the latest version (>= 7.22)

### ISSUE THREAD

**Issue by hugo4711** [autopkg/gerardkok-recipes#106]
The heroku CLI is outdated:
https://github.com/autopkg/gerardkok-recipes/blob/master/Heroku/HerokuCLI.munki.recipe

heroku-cli: update available from 6.16.18-b58c8ad to 6.99.0-ec9edad

Latest official version seems to be heroku/7.22.0 darwin-x64 node-v11.9.0

**Comment by gerardkok** [comment]
Thanks for letting me know, I'll try to fix it within a few days, but unfortunately it's not going to be trivial. It looks like Heroku has stopped distributing an up-to-date macOS package (the one listed under https://devcenter.heroku.com/articles/heroku-cli#download-and-install is not up-to-date). So I'll rewrite the recipe to download the tarball, and build a package from that. I'll try to find a few hours to do that soon.

**Comment by hugo4711** [comment]
Got the update to 7.22 so I believe this can be closed? Thanks a lot!

**Comment by gerardkok** [comment]
I got the update too, so I assume Heroku has updated the pkg. It's possible that at some point in the future the macOS pkg will start lagging behind again, but we'll cross that bridge when we get there (I prefer to use the package instead of the tarball, because the package is signed; the tarball is not).

So for now I'll close this issue, feel free to reopen if you notice the version of the pkg is lagging behind.
