### ISSUE TITLE
Can you create a jss recipe for Yubico Authenticator?

### ISSUE THREAD

**Issue by kylejericson** [autopkg/gerardkok-recipes#108]
Hey just wondering if you can create a .jss recipe for Yubico Authenticator.

**Comment by gerardkok** [comment]
I've made one, but I'm not using JAMF myself, so I can't test if it really works (or at least I think I can't test it without having JAMF installed). So I copied https://github.com/autopkg/jss-recipes/blob/master/Visual%20Studio%20Code/Visual%20Studio%20Code.jss.recipe (because that one looked straightforward), and search/replaced everything that I think needed replacing. If it doesn't work, please let me know what should be changed.

**Comment by kylejericson** [comment]
Not sure here this was for Yubico Authenticator not Visual Studio

**Comment by gerardkok** [comment]
I've made one for YubiKey Authenticator, but I used the Visual Studio Code one as a template.

**Comment by kylejericson** [comment]
idk I click this link and it's all Visual Studio.

**Comment by kylejericson** [comment]
ahh found it

**Comment by gerardkok** [comment]
Cool, good to hear. In the meantime I realised that I had the parent recipe wrong. I just fixed that.

**Comment by kylejericson** [comment]
Can you add a .pkg recipe of this?
