### ISSUE TITLE
Future of Versions.app recipe

### ISSUE THREAD

**Issue by peterkelm** [autopkg/gerardkok-recipes#171]
@gerardkok, we've used your Versions.app recipe "forever" and did of course notice the deprecation note you added. 

Versions.app has a new owner and two new versions (although primarily bug fixes and legal text changes) were released. Part of that is a developer certificate change. That prevents your recipe from finishing correctly...

Not sure what your motivation was to deprecate your Versions.app recipe - would you accept a pull request to fix your download recipe or would you prefer if I publish new recipes for Versions.app?

**Comment by gerardkok** [comment]
Hey @peterkelm, thanks for letting me know that Versions.app has a new maintainer. I put the deprecation warning on it, because I thought it was abandoned, iirc the TLS certificate on the Sparkle update feed had expired, and I didn't want to add an 'ignore TLS warning' to the download processor.

But now that that has been fixed, and the developer certificate is also correct again, I see no issue in reviving the recipe. I've removed the deprecation warning, and put the correct developer certificate in, so it should properly work again. please let me know when it doesn't.

**Comment by peterkelm** [comment]
Thanks a million - works as expected!
