### ISSUE TITLE
nodejs keeps importing to munki (force_munkiimport is True)

### ISSUE THREAD

**Issue by kcrawford** [autopkg/gerardkok-recipes#25]
Is there a reason why force_munkiimport is set to True for the nodejs recipe?

I think that is why node keeps importing into my munki repo.

**Comment by gerardkok** [comment]
I agree it's a pretty terrible recipe currently. The downloaded nodejs package currently contains no version information that munkiimport 'understands' (it has the version somewhere in there, but not in an Info.plist file, or a receipt). So when I ,made this recipe I finally gave in, and just import the package when there has been a download. This fails if you (for example) remove your downloads after every autopkg run.

I just checked the package, it is still awful, but I now think I could probably make it work by comparing checksums, instead of force_munkiimport to True. I'll revisit the recipe in a few days to see if that works.

**Comment by gerardkok** [comment]
I've rewritten the recipe to base MunkiImport on the checksums of two installs items, and made sure the receipts array is empty (this way MunkiImport won't complain that the package is already in the repo, if it's not your first import). I'm quite confident it now works, but if it doesn't, feel free to reopen this issue.
