### ISSUE TITLE
Cockpit.munki.recipe

### ISSUE THREAD

**Issue by grovetech** [autopkg/gerardkok-recipes#76]
No match found on URL: http://www.devolo.com/en/dLAN-software/devolo-Cockpit-simple-powerline-network-configuration

Looks like the URL has changed. 

The closest to a replacement URL I could find was

https://stage.at.devolo.scalecommerce.cloud/support/downloads.html#downloads166901

which just lists of products and none of them seem to offer a Cockpit download. Not sure what the issue is, could be end of life for this particular software title. Just flagging it for you in case you were not aware.

**Comment by gerardkok** [comment]
Thanks for letting me know. It appears Devolo now publishes a download url for Cockpit again: [https://stage.at.devolo.scalecommerce.cloud/support/downloads/download/devolo-cockpit.html](https://stage.at.devolo.scalecommerce.cloud/support/downloads/download/devolo-cockpit.html). I've updated the recipe to use this url. The new url is using https, so that's a plus.

**Comment by gerardkok** [comment]
Well, that worked for one day, now there's a new version that needs a new regex. So I fixed that, but now it appears the code signature is incorrect, because one of the certificates involved has expired.

**Comment by gerardkok** [comment]
I've contacted Devolo, but I don't think a properly signed Cockpit download is imminent. I've added a README explaining how to skip signature verification.
